
apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# # declaration of minimum required vendir binary version (optional)
# minimumRequiredVersion: 0.8.0

# one or more directories to manage with vendir
directories:
- # path is relative to `vendir` CLI working directory
  # This MUST be free from files not under vendir's control, otherwise it WILL delete them!
  path: apps/rollout-example/vendor

  # set the permissions for this directory (optional; v0.33.0+)
  # by default directories will be created with 0700
  # can be provided as octal, in which case it needs to be prefixed with a `0`
  permissions: 0700

  contents:
  - # path lives relative to directory path # (required)
    path: ./

    # skip fetching if the config for this path has not changed since the last sync
    # optional, `false` by default, available since v0.36.0
    # use `vendir sync --lazy=false` to forcefully sync when needed
    lazy: true
    
    includePaths:
      - blue-green/**/*

    # uses git to clone Git repository (optional)
    git:
      # http or ssh urls are supported (required)
      url: https://github.com/argoproj/argocd-example-apps.git
      # branch, tag, commit; origin is the name of the remote (required)
      # optional if refSelection is specified (available in v0.11.0+)
      ref: origin/master
      # depth of commits to fetch; 0 (default) means everything (optional; v0.29.0+)
      depth: 1
      # # specifies a strategy to resolve to an explicit ref (optional; v0.11.0+)
      # refSelection:
      #   semver:
      #     # list of semver constraints (see versions.md for details) (required)
      #     constraints: ">0.4.0"
      #     # by default prerelease versions are not included (optional; v0.12.0+)
      #     prereleases:
      #       # select prerelease versions that include given identifiers (optional; v0.12.0+)
      #       identifiers: [beta, rc]
      # skip downloading lfs files (optional)
      lfsSkipSmudge: true
      # skip SSL/TLS verification (optional)
      dangerousSkipTLSVerify: false
      # skip initializing any git submodules (optional; v0.28.0+)
      skipInitSubmodules: true
      # # verify gpg signatures on commits or tags (optional; v0.12.0+)
      # verification:
      #   publicKeysSecretRef:
      #     name: my-git-gpg-auth
