apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubesay
  #namespace: argocd # Should be set either by client or parent app

  # Ensures that resources are deleted recursively when this app is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/BronzeDeer/argocd-demo-team-a.git
    targetRevision: HEAD
    path: ./apps/kubesay/manifests

  project: default # Should be patched by parent app as needed

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
