# Same structure as in the example chart
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    # We will only be using the first for simplicity
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

  # className: nginx

  # # The other chart computes the service Name based on its helm-guestbook.fullname function
  # # If used in argoCD in the same app as the other chart, this chart auto derives the correct serviceName,
  # # however, for certainty, set serviceNameOverride in this chart and fullnameOverride in the other chart to the same value
  # serviceNameOverride: rollout-example

  # Ingress towards the preview version of the rollout
  # Only evaluted if ingress.enabled = true
  # This ingress will copy the host used by the normal ingress 
  # but add the suffix -preview to the leftmost dns component
  preview:
    # Whether to create an ingress for the preview
    enabled: true

