apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-example
  namespace: argocd # Should be set either by client or parent app

  # Ensures that resources are deleted recursively when this app is deleted
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default # Should be patched by parent app as needed
  source:
    repoURL: https://github.com/BronzeDeer/argocd-demo-team-a.git # We are loading a helm chart via git
    targetRevision: HEAD
    path: ./apps/rollout-example/vendor/blue-green

    helm:
      valuesObject:
        image:
          tag: "0.1" # We will use this to trigger a rollout

        ingress:
          enabled: true
          # Parent app should pass relevant ingress values


  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
