---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-echo-back
  name: http-echo-back
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: http-echo-back
status:
  loadBalancer: {}
